### ISSUE TITLE
A plugin to force survival mode in certain zones

### ISSUE THREAD

**Issue by thorva** [chicken-mover/NUDEL#1]
Assuming this isn't already possible, a plugin would force you into survival mode, preferably when you entered a WorldGuard zone. Should be called "Huwawa".

**Comment by petronius** [comment]
A plugin would be a cleaner solution than anything hacked together with command blocks, certainly.

**Comment by petronius** [comment]
Closing, as the plugin has been started, and is now entering testing phase. See 89418acd6c46f50a2358ac647130eb63980c76d3
